### ISSUE TITLE
Trying to Diagnose: cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL

### ISSUE THREAD

**Issue by HeathMorrisCode** [nao-pon/flysystem-google-drive#43]
Hi Everyone, 

I'm trying to figure out this error that happens a couple of times a day (the rest of the time everything works great). It doesn't seem to be related to anything I'm doing in particular (like one drive api endpoint over another). It can happen on deleting a folder, or on listing files in a folder, just intermittent.

The main message is:

cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.googleapis.com:443

This seems like it would be easier to diagnose if I was totally blocked from the beginning, and couldn't access Drive through the API at all. I would assume in that case that I had screwed up getting the tokens in the beginning or something like that. The stack trace mentions the refresh token, but again, 99% of the time my app works just fine with Drive.

Perhaps it is a problem with obtaining a new token token? And then it starts working again after it has a new token? Any ideas of how I could proceed with troubleshooting this would be super helpful! Stack trace pasted below:

[2018-06-25 01:54:22] local.ERROR: cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.googleapis.com:443  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) {"userId":9,"email":"heathmorriscode@gmail.com","exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.googleapis.com:443  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) at /home/vagrant/code/stables/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185)
[stacktrace]
#0 /home/vagrant/code/stables/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\\Handler\\CurlFactory::createRejection(Object(GuzzleHttp\\Handler\\EasyHandle), Array)
#1 /home/vagrant/code/stables/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\\Handler\\CurlFactory::finishError(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))
#2 /home/vagrant/code/stables/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))
#3 /home/vagrant/code/stables/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#4 /home/vagrant/code/stables/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#5 /home/vagrant/code/stables/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#6 /home/vagrant/code/stables/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#7 /home/vagrant/code/stables/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#8 /home/vagrant/code/stables/vendor/guzzlehttp/guzzle/src/Middleware.php(58): GuzzleHttp\\RedirectMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#9 /home/vagrant/code/stables/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#10 /home/vagrant/code/stables/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\\HandlerStack->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#11 /home/vagrant/code/stables/vendor/guzzlehttp/guzzle/src/Client.php(99): GuzzleHttp\\Client->transfer(Object(GuzzleHttp\\Psr7\\Request), Array)
#12 /home/vagrant/code/stables/vendor/guzzlehttp/guzzle/src/Client.php(106): GuzzleHttp\\Client->sendAsync(Object(GuzzleHttp\\Psr7\\Request), Array)
#13 /home/vagrant/code/stables/vendor/google/auth/src/HttpHandler/Guzzle6HttpHandler.php(34): GuzzleHttp\\Client->send(Object(GuzzleHttp\\Psr7\\Request), Array)
#14 /home/vagrant/code/stables/vendor/google/auth/src/OAuth2.php(501): Google\\Auth\\HttpHandler\\Guzzle6HttpHandler->__invoke(Object(GuzzleHttp\\Psr7\\Request))
#15 /home/vagrant/code/stables/vendor/google/apiclient/src/Google/Client.php(277): Google\\Auth\\OAuth2->fetchAuthToken(Object(Google\\Auth\\HttpHandler\\Guzzle6HttpHandler))
#16 /home/vagrant/code/stables/vendor/google/apiclient/src/Google/Client.php(254): Google_Client->fetchAccessTokenWithRefreshToken('1/b6oP5VDeBV1zV...')
#17 /home/vagrant/code/stables/app/Providers/GoogleDriveServiceProvider.php(17): Google_Client->refreshToken('1/b6oP5VDeBV1zV...')
#18 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(139): App\\Providers\\GoogleDriveServiceProvider->App\\Providers\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#19 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(119): Illuminate\\Filesystem\\FilesystemManager->callCustomCreator(Array)
#20 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(103): Illuminate\\Filesystem\\FilesystemManager->resolve('google')
#21 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(80): Illuminate\\Filesystem\\FilesystemManager->get('google')
#22 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemManager.php(67): Illuminate\\Filesystem\\FilesystemManager->disk('google')
#23 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Filesystem\\FilesystemManager->drive('google')
#24 /home/vagrant/code/stables/app/Http/Controllers/EventController.php(149): Illuminate\\Support\\Facades\\Facade::__callStatic('drive', Array)
#25 [internal function]: App\\Http\\Controllers\\EventController->destroy(Object(App\\Event))
#26 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#27 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('destroy', Array)
#28 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\EventController), 'destroy')
#29 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#30 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Router.php(665): Illuminate\\Routing\\Route->run()
#31 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#32 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#52 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#53 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Router.php(608): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#54 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Router.php(597): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#55 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#56 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#57 /home/vagrant/code/stables/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#58 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /home/vagrant/code/stables/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#64 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#67 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#70 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(51): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#73 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#76 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#77 /home/vagrant/code/stables/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#78 /home/vagrant/code/stables/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#79 {main}
"} 

Thanks for checking it out! Any ideas are welcome and appreciated.

I've also tried restarting my vagrant box and updating the time on it, in case a time mismatch was causing issues. Strangely, when the error happens, I can load app pages in a separate tab which list files from certain drive folders just fine (using this drive api library and the same credentials), but the action I was doing in the first tab will keep throwing this error until a couple minutes has gone by.

**Comment by HeathMorrisCode** [comment]
Didn't mean to reference every single issue in this repo! It happened when I pasted the stack trace outside of a code-block, not sure how to undo it.
