### ISSUE TITLE
Google_Exception: (list) unknown parameter: 'maxResults'

### ISSUE THREAD

**Issue by laurentvd** [nao-pon/flysystem-google-drive#5]
Hi! I've probably misconfigured something, but I'm getting `unknown parameter: 'maxResults'` errors. I've done some digging and it seems that Google API v2 used `maxResults` where v3 uses `pageSize`. Any ideas? Here's the relevant stack trace:

```
Could not connect to disk google because: Google_Exception: (list) unknown parameter: 'maxResults' in /home/vagrant/app/vendor/google/apiclient/src/Google/Service/Resource.php:151
Stack trace:
#0 /home/vagrant/app/vendor/google/apiclient/src/Google/Service/Drive.php(1131): Google_Service_Resource->call('list', Array, 'Google_Service_...')
#1 /home/vagrant/app/vendor/nao-pon/flysystem-google-drive/src/GoogleDriveAdapter.php(749): Google_Service_Drive_Files_Resource->listFiles(Array)
#2 /home/vagrant/app/vendor/nao-pon/flysystem-google-drive/src/GoogleDriveAdapter.php(399): Hypweb\Flysystem\GoogleDrive\GoogleDriveAdapter->getItems('my-folder...', true)
#3 /home/vagrant/app/vendor/league/flysystem-cached-adapter/src/CachedAdapter.php(233): Hypweb\Flysystem\GoogleDrive\GoogleDriveAdapter->listContents('my-folder...', true)
#4 /home/vagrant/app/vendor/league/flysystem/src/Filesystem.php(270): League\Flysystem\Cached\CachedAdapter->listContents('my-folder...', true)
#5 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(257): League\Flysystem\Filesystem->listContents('my-folder...', true)
#6 /home/vagrant/app/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(270): Illuminate\Filesystem\FilesystemAdapter->files('my-folder...', true)
```

**Comment by laurentvd** [comment]
Never mind, it was mentioned in the readme that 1.1 is for V3. Apparently I was using V3 (not sure how or why), so upgrading from 1.0 to 1.1 fixes the issue. Well actually, it raises another issue, but this particular issue is closed. Sorry for the distraction ;)
